<script lang="ts">
  import {
    Search,
    Plus,
    X,
    ChevronRight,
    ChevronDown,
    RefreshCw,
    Command,
    Keyboard,
    LogOut,
    FunnelX,
    ArrowUp,
    ArrowDown,
    Tag,
    User,
    CircleDashed,
    Circle,
    CircleDot,
    GitPullRequest,
    OctagonAlert,
    CircleCheck,
    CircleSlash,
    SquareCheck,
    Bug,
    Sparkles,
    Info,
    Check,
    Hash,
    UserX,
    CircleDotDashed,
    UserPlus,
    ChevronLeft,
    Ellipsis,
    ListFilter,
    Eye,
    Shield,
    Terminal,
    Trash2,
    KeyRound,
    Copy,
  } from '@lucide/svelte';

  let {
    name,
    size = 16,
    strokeWidth = 1.75,
  }: { name: string; size?: number; strokeWidth?: number } = $props();
  const icons = {
    search: Search,
    plus: Plus,
    close: X,
    arrow: ChevronRight,
    down: ChevronDown,
    refresh: RefreshCw,
    command: Command,
    keyboard: Keyboard,
    logout: LogOut,
    'clear-filter': FunnelX,
    up: ArrowUp,
    'arrow-down': ArrowDown,
    tag: Tag,
    person: User,
    info: Info,
    check: Check,
    hash: Hash,
    unassigned: UserX,
    status: CircleDotDashed,
    'add-person': UserPlus,
    back: ChevronLeft,
    more: Ellipsis,
    filter: ListFilter,
    eye: Eye,
    shield: Shield,
    terminal: Terminal,
    trash: Trash2,
    key: KeyRound,
    copy: Copy,
    // Statuses
    backlog: CircleDashed,
    todo: Circle,
    in_progress: CircleDot,
    code_review: GitPullRequest,
    blocked: OctagonAlert,
    complete: CircleCheck,
    void: CircleSlash,
    // Item types
    task: SquareCheck,
    bug: Bug,
    feature: Sparkles,
  };
  let Glyph = $derived(icons[name as keyof typeof icons] || Circle);
</script>

<Glyph {size} {strokeWidth} aria-hidden="true" focusable="false" />
